### ISSUE TITLE
Doenst work in react 16.0.0

### ISSUE THREAD

**Issue by wietzehiha** [leejaen/React-Desktop-Notification#5]
TypeError: React.createClass is not a function
./node_modules/react-desktop-notification/index.js
node_modules/react-desktop-notification/index.js:6
  3 |  */
  4 | var React = require('react');
  5 | 
> 6 | var Notifier = React.createClass({
  7 |   statics: {
  8 |     start: function(title, context, url, icon, name) {
  9 |       name=name||("notiwin"+(function(n) {

**Comment by applebaum** [comment]
@wietzehiha, here's [version that supports React v16](https://github.com/applebaum/react-desktop-notifications)

**Comment by wietzehiha** [comment]
Thankyou!
